name: Health check pipeline

# Scheduled trigger for health check every day at 6:45 AM
on:
  schedule:
    - cron: '45 6 * * *'

# Manual trigger just for testing purposes
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#     types:
#       - opened
#       - synchronize

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Health check action
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          url: ${{ secrets.RENDER_URL }}/health