name: Health check pipeline

# on:
#   schedule:
#     - cron: '6 45 * * *'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Health check action
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          url: ${{ secrets.RENDER_URL }}/health