name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build

      # Jest
      - name: Test
        run: npm run test

      # Playwright
      - name: Install Playwright Browsers
        if: ${{ github.actor != 'nektos/act' }}
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        if: ${{ github.actor != 'nektos/act' }}
        run: npm run test:e2e

      - name: Render Deployment
        if: ${{ github.event_name == 'push' && github.actor != 'nektos/act' }}
        uses: sws2apps/render-deployment@v2.0.0 
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}

      # Notify Discord (Success)
      - name: Actions for Discord (Success)
        if: ${{ success() && github.event_name == 'push' && github.actor != 'nektos/act' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": "✅ Deployment Succeeded",
                "description": "The project **${{ github.repository }}** has been successfully deployed on branch `${{ github.ref_name }}`.",
                "color": 5763719 
              }
            ]
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
      
      # Notify Discord (Failure)
      - name: Actions for Discord (Failure)
        if: ${{ failure()  && github.event_name == 'push' && github.actor != 'nektos/act' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": "❌ Deployment Failed",
                "description": "The project **${{ github.repository }}** has failed to deploy on branch `${{ github.ref_name }}`.",
                "color": 15548997
              }
            ]
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has failed to deploy.'

  tag_release:
    needs: 
      - simple_deployment_pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Debug info
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      # Bump version
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push'}}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          PRERELEASE: true
